### ISSUE TITLE
java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet

### ISSUE THREAD

**Issue by ckrgithub** [samlss/CoffeeView#1]
启动报错：java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet.

**Comment by samlss** [comment]
> 启动报错：java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet.

麻烦贴一下完整的报错log

**Comment by samlss** [comment]
> 启动报错：java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet.

有可能是复用AnimatorSet的问题，我已经修改部分代码升级版本为1.1，麻烦你重新测试看看是否依旧存在此问题！

**Comment by ckrgithub** [comment]
> > 启动报错：java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet.
> 
> 有可能是复用AnimatorSet的问题，我已经修改部分代码升级版本为1.1，麻烦你重新测试看看是否依旧存在此问题！

1.1没问题了
